### ISSUE TITLE
Error when clicking on config

### ISSUE THREAD

**Issue by yougnut** [avanteGarbage/DuoMed#8]
Hi, I ran into this error message when clicking on config, would greatly appreciate it if you could spare some time to look into it, thanks.

Anki 24.04 (429bc9e1)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22621

Traceback (most recent call last):
  File "aqt.addons", line 1024, in onConfig
  File "C:\Users\Kavin\AppData\Roaming\Anki2\addons21\255048658\settings_window.py", line 96, in DuoMedSettings
    d = MyUIDialog()
  File "C:\Users\Kavin\AppData\Roaming\Anki2\addons21\255048658\settings_window.py", line 90, in __init__
    QDialog.__init__(self, parent, aqt.Qt.Window)
AttributeError: type object 'Qt' has no attribute 'Window'

**Comment by yougnut** [comment]
To add to this, I later discovered that the config file can only be edited when this add-on is disabled, I hope this information is helpful.

**Comment by avanteGarbage** [comment]
should be fixed with most recent update!
